-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 22:46:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ttcn-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ttcn-ecommerce` ;

-- -----------------------------------------------------
-- Schema ttcn-ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ttcn-ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `ttcn-ecommerce` ;

-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`category` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `thumbnail` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;



-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`role` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`customer` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `gender` INT NULL DEFAULT NULL,
  `enabled` INT NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile_picture` VARCHAR(200) NULL DEFAULT NULL,
  `role_id` BIGINT NULL DEFAULT NULL,
  `provider` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKo2oh87rk6lunf0lic1svc9y75` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKo2oh87rk6lunf0lic1svc9y75`
    FOREIGN KEY (`role_id`)
    REFERENCES `ttcn-ecommerce`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`employee` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`employee` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `gender` INT NULL DEFAULT NULL,
  `enabled` INT NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile_picture` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`cart` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `total_cost` DECIMAL(19,2) NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK624gtjin3po807j3vix093tlf` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FK624gtjin3po807j3vix093tlf`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ttcn-ecommerce`.`customer` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`product` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `short_description` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `brand` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DECIMAL(19,2) NULL DEFAULT NULL,
  `thumbnail` VARCHAR(200) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1mtsbur82frn64de7balymq9s` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK1mtsbur82frn64de7balymq9s`
    FOREIGN KEY (`category_id`)
    REFERENCES `ttcn-ecommerce`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`feedback` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`feedback` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1mtsbur82frn64de7balymq9k` (`product_id` ASC) VISIBLE,
  INDEX `FK1mtsbus82frn64de7balymq9d` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FK1mtsbur82frn64de7balymq9k`
    FOREIGN KEY (`product_id`)
    REFERENCES `ttcn-ecommerce`.`product` (`id`),
  CONSTRAINT `FK1mtsbus82frn64de7balymq9d`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ttcn-ecommerce`.`customer` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `createdby` VARCHAR(255) NULL DEFAULT NULL,
  `createddate` DATETIME(6) NULL DEFAULT NULL,
  `modifiedby` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME(6) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `cart_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `status` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `FKlt3mrhyikkt94xukyqrv652jd` (`cart_id` ASC) VISIBLE,
  INDEX `FKdfk89kr9xleu3aljo18y2lyec` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKdfk89kr9xleu3aljo18y2lyec`
    FOREIGN KEY (`product_id`)
    REFERENCES `ttcn-ecommerce`.`product` (`id`),
  CONSTRAINT `FKlt3mrhyikkt94xukyqrv652jd`
    FOREIGN KEY (`cart_id`)
    REFERENCES `ttcn-ecommerce`.`cart` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `ttcn-ecommerce`.`employee_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ttcn-ecommerce`.`employee_role` ;

CREATE TABLE IF NOT EXISTS `ttcn-ecommerce`.`employee_role` (
  `employee_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ttcn-ecommerce`.`employee` (`id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `ttcn-ecommerce`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
